# to activate/deactivate travisCI - go to https://travis-ci.org/, sign
# in with guthub, and follow instructions

language: python
python:
  - "2.7"

before_install:
  - "./swarmwrapper.py install --prefix $VIRTUAL_ENV"

script:
  - ./test.sh

notifications:
  email:
    - noah.hoffman@gmail.com
